export const districtsSaoJose = [
  "Área Rural de São José",
  "Areias",
  "Barreiros",
  "Bela Vista",
  "Bosque das Mansões",
  "Campinas",
  "Centro",
  "Colônia Santana",
  "Distrito Industrial",
  "Fazenda Santo Antônio",
  "Flor de Nápolis",
  "Forquilhas",
  "Forquilhinha",
  "Ipiranga",
  "Jardim Cidade de Florianópolis",
  "Jardim Santiago",
  "Kobrasol",
  "Nossa Senhora do Rosário",
  "Pedregal",
  "Picadas do Sul",
  "Potecas",
  "Praia Comprida",
  "Roçado",
  "Serraria",
  "São Luiz",
  "Ponta de Baixo",
  "Real Parque"
];